meta:
  app_id: ocp_sync_source_reference_app
  display_name: Shopify Source Sync Reference App
  version: 1.0.0-dev.1
  vendor: optimizely
  summary: Shopify Source Sync Reference App
  support_url: https://support.optimizely.com
  contact_email: support@optimizely.com
  categories:
    - Commerce Platform
  availability:
    - all

runtime: node22

sources:
  Product:
    description: Shopify Product
    schema: shopify_products

jobs:
  import_products:
    entry_point: ImportProducts
    description: Performs a one-time import of all Shopify products
